// Imported via `expo/config-plugins` rather than `@expo/config-plugins`:
// pnpm's strict node_modules doesn't hoist the latter, so a direct require
// fails to resolve from Gradle's expo-constants task.
const { withMainActivity, createRunOncePlugin } = require("expo/config-plugins");

/**
 * react-native-health-connect requires the host Activity to register its
 * permission-result launcher before the Activity starts:
 *
 *   HealthConnectPermissionDelegate.setPermissionDelegate(this)
 *
 * The library ships an Expo plugin, but it only handles the manifest — it does
 * not patch MainActivity. Without this call, `requestPermission()` throws
 *
 *   UninitializedPropertyAccessException: lateinit property requestPermission
 *   has not been initialized
 *
 * and takes the whole app down the moment the athlete taps "Connect your watch".
 *
 * MainActivity.kt is generated by prebuild and gitignored, so patching it by
 * hand wouldn't survive `expo prebuild --clean`. Hence this plugin.
 */

const IMPORT = "import dev.matinzd.healthconnect.permissions.HealthConnectPermissionDelegate";
const CALL = "HealthConnectPermissionDelegate.setPermissionDelegate(this)";

function addHealthConnectDelegate(src) {
  if (src.includes(CALL)) return src;

  let out = src;

  // Import goes after the package declaration.
  if (!out.includes(IMPORT)) {
    out = out.replace(/^(package .+\n)/m, `$1\n${IMPORT}\n`);
  }

  // registerForActivityResult must run before the Activity reaches STARTED,
  // so the call sits immediately after super.onCreate(...).
  const superCall = /(\n(\s*)super\.onCreate\([^)]*\)\n)/;
  if (!superCall.test(out)) {
    throw new Error(
      "withHealthConnectPermissionDelegate: could not find super.onCreate() in MainActivity",
    );
  }
  out = out.replace(superCall, (_m, line, indent) => `${line}${indent}${CALL}\n`);

  return out;
}

const withHealthConnectPermissionDelegate = (config) =>
  withMainActivity(config, (cfg) => {
    if (cfg.modResults.language !== "kt") {
      throw new Error(
        "withHealthConnectPermissionDelegate: expected a Kotlin MainActivity",
      );
    }
    cfg.modResults.contents = addHealthConnectDelegate(cfg.modResults.contents);
    return cfg;
  });

module.exports = createRunOncePlugin(
  withHealthConnectPermissionDelegate,
  "with-health-connect-permission-delegate",
  "1.0.0",
);
